// Package keycloakadmin wraps the small slice of Keycloak's Admin REST
// API that the identity service needs:
//
//   - acquire an admin access token via the `admin-cli` client in the
//     master realm (password grant)
//   - create a confidential client (service-account enabled) in the
//     `guva` realm
//   - fetch the generated client secret so the caller can hand it to
//     the consumer once
//
// No external dependencies — direct net/http against the Admin REST
// endpoints. The same restraint as pkg/secrets: the Keycloak Go SDK
// surface is large for the four calls we make.
package keycloakadmin

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"strings"
	"sync"
	"time"
)

// Config captures the per-process inputs to NewClient.
type Config struct {
	// BaseURL is the URL the identity service reaches Keycloak at.
	// In local dev (identity runs on host) this is http://localhost:8080.
	// In-cluster it's typically http://keycloak:8080. Do NOT use the
	// Caddy-fronted https URL — that would require trusting Caddy's CA
	// inside the identity container. Use plain HTTP in-network.
	BaseURL string

	// Realm is the target realm for client management (e.g. "guva").
	Realm string

	// AdminUser / AdminPassword authenticate against the `admin-cli`
	// client in the `master` realm. AdminPassword should come from a
	// secret store — see services/identity/cmd/server/main.go.
	AdminUser     string
	AdminPassword string

	// HTTPClient overrides the underlying client; optional.
	HTTPClient *http.Client
}

// Client is the admin API wrapper. Safe for concurrent use; admin token
// cache is mutex-guarded.
type Client struct {
	cfg  Config
	http *http.Client

	mu          sync.Mutex
	cachedToken string
	expiresAt   time.Time
}

// Errors callers may want to special-case.
var (
	ErrClientExists      = errors.New("keycloak client with that clientId already exists")
	ErrAdminCredentials  = errors.New("admin authentication failed; check username/password")
	ErrRealmNotFound     = errors.New("realm not found")
	ErrUnknownAdminError = errors.New("keycloak admin API error")
)

// NewClient validates config and returns a Client ready to use.
func NewClient(cfg Config) (*Client, error) {
	if cfg.BaseURL == "" {
		return nil, errors.New("keycloakadmin: BaseURL is required")
	}
	if cfg.Realm == "" {
		return nil, errors.New("keycloakadmin: Realm is required")
	}
	if cfg.AdminUser == "" || cfg.AdminPassword == "" {
		return nil, errors.New("keycloakadmin: AdminUser and AdminPassword are required")
	}
	if cfg.HTTPClient == nil {
		cfg.HTTPClient = &http.Client{Timeout: 10 * time.Second}
	}
	cfg.BaseURL = strings.TrimRight(cfg.BaseURL, "/")
	return &Client{cfg: cfg, http: cfg.HTTPClient}, nil
}

// CreateClientRequest is what the caller hands to CreateConfidentialClient.
type CreateClientRequest struct {
	ClientID            string   // e.g. "acacia-onboarding"
	Name                string   // human-readable name
	DefaultClientScopes []string // realm-level client-scope names to grant
}

// CreateClientResult carries the values the caller must persist or
// hand off. The Secret is generated by Keycloak and is the ONLY time
// it's available in plaintext — callers must show it to the consumer
// at registration time and never store it themselves.
type CreateClientResult struct {
	InternalID string // Keycloak's UUID for the client (used for /clients/{id} ops)
	ClientID   string // The caller-supplied clientId, echoed for confirmation
	Secret     string // Generated client secret (one-time disclosure)
}

// CreateConfidentialClient creates a service-account-enabled client in
// the realm, then fetches and returns its generated secret.
//
// The created client has:
//   - protocol: openid-connect
//   - publicClient: false (i.e. a confidential client with a secret)
//   - serviceAccountsEnabled: true (allows client_credentials grant)
//   - standardFlowEnabled: false, directAccessGrantsEnabled: false
//
// On clientId conflict the function returns ErrClientExists; callers
// should map that to HTTP 409.
func (c *Client) CreateConfidentialClient(ctx context.Context, req CreateClientRequest) (CreateClientResult, error) {
	if strings.TrimSpace(req.ClientID) == "" {
		return CreateClientResult{}, errors.New("keycloakadmin: ClientID is required")
	}

	token, err := c.adminToken(ctx)
	if err != nil {
		return CreateClientResult{}, err
	}

	createBody := map[string]any{
		"clientId":                  req.ClientID,
		"name":                      req.Name,
		"protocol":                  "openid-connect",
		"publicClient":              false,
		"serviceAccountsEnabled":    true,
		"standardFlowEnabled":       false,
		"directAccessGrantsEnabled": false,
		"clientAuthenticatorType":   "client-secret",
		"defaultClientScopes":       req.DefaultClientScopes,
	}
	bodyBytes, err := json.Marshal(createBody)
	if err != nil {
		return CreateClientResult{}, fmt.Errorf("marshal: %w", err)
	}

	createURL := fmt.Sprintf("%s/admin/realms/%s/clients", c.cfg.BaseURL, c.cfg.Realm)
	httpReq, err := http.NewRequestWithContext(ctx, http.MethodPost, createURL, bytes.NewReader(bodyBytes))
	if err != nil {
		return CreateClientResult{}, err
	}
	httpReq.Header.Set("Authorization", "Bearer "+token)
	httpReq.Header.Set("Content-Type", "application/json")

	resp, err := c.http.Do(httpReq)
	if err != nil {
		return CreateClientResult{}, fmt.Errorf("create client: %w", err)
	}
	defer func() { _ = resp.Body.Close() }()

	switch resp.StatusCode {
	case http.StatusCreated:
		// success — proceed
	case http.StatusConflict:
		return CreateClientResult{}, ErrClientExists
	case http.StatusNotFound:
		return CreateClientResult{}, ErrRealmNotFound
	case http.StatusUnauthorized, http.StatusForbidden:
		return CreateClientResult{}, ErrAdminCredentials
	default:
		body, _ := io.ReadAll(io.LimitReader(resp.Body, 1024))
		return CreateClientResult{}, fmt.Errorf("%w: %s: %s", ErrUnknownAdminError, resp.Status, strings.TrimSpace(string(body)))
	}

	// Keycloak returns the new resource's URL in the Location header.
	// The final path segment is the client's internal UUID.
	loc := resp.Header.Get("Location")
	if loc == "" {
		return CreateClientResult{}, errors.New("keycloak created the client but returned no Location header")
	}
	internalID := loc[strings.LastIndex(loc, "/")+1:]

	secret, err := c.fetchClientSecret(ctx, token, internalID)
	if err != nil {
		return CreateClientResult{}, fmt.Errorf("fetch generated secret: %w", err)
	}

	return CreateClientResult{
		InternalID: internalID,
		ClientID:   req.ClientID,
		Secret:     secret,
	}, nil
}

// ClientScope is the Keycloak ClientScopeRepresentation, trimmed to the
// fields we use.
type ClientScope struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Protocol    string `json:"protocol"`
}

// ListClientScopes returns every client-scope in the realm. Keycloak
// includes both our platform scopes (`verify:citizen`, `audit:read`, …)
// and built-in OpenID Connect ones (`profile`, `email`, `openid`, …);
// the caller filters as needed.
func (c *Client) ListClientScopes(ctx context.Context) ([]ClientScope, error) {
	token, err := c.adminToken(ctx)
	if err != nil {
		return nil, err
	}
	url := fmt.Sprintf("%s/admin/realms/%s/client-scopes", c.cfg.BaseURL, c.cfg.Realm)
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, url, nil)
	if err != nil {
		return nil, err
	}
	req.Header.Set("Authorization", "Bearer "+token)
	resp, err := c.http.Do(req)
	if err != nil {
		return nil, fmt.Errorf("list client-scopes: %w", err)
	}
	defer func() { _ = resp.Body.Close() }()
	if resp.StatusCode/100 != 2 {
		body, _ := io.ReadAll(io.LimitReader(resp.Body, 1024))
		return nil, fmt.Errorf("list client-scopes: %s: %s", resp.Status, strings.TrimSpace(string(body)))
	}
	var scopes []ClientScope
	if err := json.NewDecoder(resp.Body).Decode(&scopes); err != nil {
		return nil, fmt.Errorf("decode client-scopes: %w", err)
	}
	return scopes, nil
}

// DeleteClient removes a client from the realm by its internal UUID.
// Used as the compensating action when our own persistence fails after
// a successful CreateConfidentialClient — without this we leave orphan
// clients behind in Keycloak that no one knows about.
//
// Returns nil for "client doesn't exist" (404) so callers can use this
// as a best-effort cleanup without special-casing.
func (c *Client) DeleteClient(ctx context.Context, internalID string) error {
	token, err := c.adminToken(ctx)
	if err != nil {
		return err
	}
	url := fmt.Sprintf("%s/admin/realms/%s/clients/%s", c.cfg.BaseURL, c.cfg.Realm, internalID)
	req, err := http.NewRequestWithContext(ctx, http.MethodDelete, url, nil)
	if err != nil {
		return err
	}
	req.Header.Set("Authorization", "Bearer "+token)
	resp, err := c.http.Do(req)
	if err != nil {
		return fmt.Errorf("delete client: %w", err)
	}
	defer func() { _ = resp.Body.Close() }()
	switch resp.StatusCode {
	case http.StatusNoContent, http.StatusNotFound:
		return nil
	case http.StatusUnauthorized, http.StatusForbidden:
		return ErrAdminCredentials
	default:
		body, _ := io.ReadAll(io.LimitReader(resp.Body, 1024))
		return fmt.Errorf("%w: %s: %s", ErrUnknownAdminError, resp.Status, strings.TrimSpace(string(body)))
	}
}

// fetchClientSecret pulls the generated secret for a freshly created
// client. The realm endpoint is /admin/realms/{realm}/clients/{id}/client-secret.
func (c *Client) fetchClientSecret(ctx context.Context, adminToken, internalID string) (string, error) {
	url := fmt.Sprintf("%s/admin/realms/%s/clients/%s/client-secret", c.cfg.BaseURL, c.cfg.Realm, internalID)
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, url, nil)
	if err != nil {
		return "", err
	}
	req.Header.Set("Authorization", "Bearer "+adminToken)
	resp, err := c.http.Do(req)
	if err != nil {
		return "", err
	}
	defer func() { _ = resp.Body.Close() }()
	if resp.StatusCode/100 != 2 {
		body, _ := io.ReadAll(io.LimitReader(resp.Body, 1024))
		return "", fmt.Errorf("get client-secret: %s: %s", resp.Status, strings.TrimSpace(string(body)))
	}

	var payload struct {
		Value string `json:"value"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&payload); err != nil {
		return "", fmt.Errorf("decode client-secret response: %w", err)
	}
	if payload.Value == "" {
		return "", errors.New("keycloak returned an empty client secret")
	}
	return payload.Value, nil
}

// adminToken returns a cached admin access token, refreshing it lazily
// when it's missing or near expiry. Two-minute grace window before
// expiry to avoid race-condition failures.
func (c *Client) adminToken(ctx context.Context) (string, error) {
	c.mu.Lock()
	defer c.mu.Unlock()

	if c.cachedToken != "" && time.Until(c.expiresAt) > 2*time.Minute {
		return c.cachedToken, nil
	}

	tokenURL := fmt.Sprintf("%s/realms/master/protocol/openid-connect/token", c.cfg.BaseURL)
	form := strings.NewReader(
		"grant_type=password" +
			"&client_id=admin-cli" +
			"&username=" + c.cfg.AdminUser +
			"&password=" + c.cfg.AdminPassword,
	)
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, tokenURL, form)
	if err != nil {
		return "", err
	}
	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")

	resp, err := c.http.Do(req)
	if err != nil {
		return "", fmt.Errorf("admin token request: %w", err)
	}
	defer func() { _ = resp.Body.Close() }()

	if resp.StatusCode == http.StatusUnauthorized || resp.StatusCode == http.StatusForbidden {
		return "", ErrAdminCredentials
	}
	if resp.StatusCode/100 != 2 {
		body, _ := io.ReadAll(io.LimitReader(resp.Body, 1024))
		return "", fmt.Errorf("admin token: %s: %s", resp.Status, strings.TrimSpace(string(body)))
	}

	var payload struct {
		AccessToken string `json:"access_token"`
		ExpiresIn   int    `json:"expires_in"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&payload); err != nil {
		return "", fmt.Errorf("decode admin token response: %w", err)
	}
	if payload.AccessToken == "" {
		return "", errors.New("admin token response missing access_token")
	}

	c.cachedToken = payload.AccessToken
	c.expiresAt = time.Now().Add(time.Duration(payload.ExpiresIn) * time.Second)
	return c.cachedToken, nil
}
