// Package tlsbundle loads X.509 cert / key / CA material into a
// *tls.Config that can be handed straight to net/http's Server and
// Transport. Two use cases:
//
//   - **Server mTLS** — the service accepts only TLS connections whose
//     peer presents a client cert signed by the configured CA. Wire
//     via httpserver.Config.TLS; APISIX (the gateway) is the expected
//     client and presents its own service identity. Direct browser /
//     curl access without a cert is rejected.
//   - **Client mTLS** — outbound HTTP calls present this service's cert
//     to the peer (e.g. service-to-service via a Keycloak admin REST,
//     a future inter-service RPC). Wire via NewClientConfig().
//
// In dev the cert material is generated by `make mint-service-certs`
// from a one-shot dev CA living under .cache/dev-ca/. In production,
// certs come from SPIFFE/SPIRE or a service mesh's per-pod sidecar;
// the loader signature is the same, only the mount paths change.
package tlsbundle

import (
	"crypto/tls"
	"crypto/x509"
	"errors"
	"fmt"
	"os"
)

// Bundle is a parsed cert/key/CA triplet plus the tls.Config built
// from them. Hold one per service.
type Bundle struct {
	cert    tls.Certificate
	roots   *x509.CertPool
	CertPEM []byte // raw PEM, useful for diagnostics / health endpoints
	CAPEM   []byte
}

// Config captures the file paths to load. All three are required.
type Config struct {
	CertFile string // server cert (and the client cert when used outbound)
	KeyFile  string // private key matching CertFile
	CAFile   string // bundle of CAs we trust when verifying the peer
}

// Load reads the cert / key / CA from disk and returns a usable Bundle.
// Returns a clear error pointing at the missing or unreadable file so
// operators can diagnose without guessing.
func Load(cfg Config) (*Bundle, error) {
	if cfg.CertFile == "" || cfg.KeyFile == "" || cfg.CAFile == "" {
		return nil, errors.New("tlsbundle.Load: CertFile, KeyFile and CAFile are all required")
	}
	cert, err := tls.LoadX509KeyPair(cfg.CertFile, cfg.KeyFile)
	if err != nil {
		return nil, fmt.Errorf("load keypair: %w", err)
	}
	caPEM, err := os.ReadFile(cfg.CAFile)
	if err != nil {
		return nil, fmt.Errorf("read CA file: %w", err)
	}
	roots := x509.NewCertPool()
	if !roots.AppendCertsFromPEM(caPEM) {
		return nil, fmt.Errorf("CA file at %s did not contain any usable certificates", cfg.CAFile)
	}
	certPEM, _ := os.ReadFile(cfg.CertFile)
	return &Bundle{cert: cert, roots: roots, CertPEM: certPEM, CAPEM: caPEM}, nil
}

// ServerConfig returns a *tls.Config suitable for an HTTP server that
// requires the peer to present a client cert signed by the CA. The
// minimum TLS version is 1.3 — we control both ends, no reason to
// allow anything older.
func (b *Bundle) ServerConfig() *tls.Config {
	return &tls.Config{
		Certificates: []tls.Certificate{b.cert},
		ClientCAs:    b.roots,
		ClientAuth:   tls.RequireAndVerifyClientCert,
		MinVersion:   tls.VersionTLS13,
	}
}

// ClientConfig returns a *tls.Config suitable for an HTTP client that
// presents this bundle's cert to a peer and verifies the peer's cert
// against the CA.
func (b *Bundle) ClientConfig() *tls.Config {
	return &tls.Config{
		Certificates: []tls.Certificate{b.cert},
		RootCAs:      b.roots,
		MinVersion:   tls.VersionTLS13,
	}
}
